# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET http://localhost:8000/api/sensors/sensors/
Content-Type: application/json

###

# создание датчика
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "Main",
  "description": "Датчик в коридоре"
}

###

# обновление датчика
PATCH http://localhost:8000/api/sensors/2/
Content-Type: application/json

{
  "description": "Перенесла датчик на балкон"
}

###

# добавление измерения
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor_id": 3,
  "temperature": 20
}

###

# получение информации по датчику
GET http://localhost:8000/api/sensors/3/
Content-Type: application/json
